server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_service
    username: root
    password: Ashu@123

  application:
    name: Hotel Service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect